### ISSUE TITLE
Installed The Dwolla Magento but not redirecting for payment.

### ISSUE THREAD

**Issue by moneygirl1** [Dwolla/dwolla-magento#2]
Please help. Site stalls when I click on place order using dwolla Magento any suggestion on fixing the issue. Already try removing and re-installing.  Also try a manual install and the problem still occurs.

**Comment by mach-kernel** [comment]
@moneygirl1,

We've taken note of this and our support staff is going to engage you by the end of the day, I will personally be looking at it with a colleague of mine because we want to get this ironed out for you ASAP.

Thank you,

David

**Comment by Outdoorsman** [comment]
So is this issues still open and more importantly are you guys still supporting this extension... does it still work in the latest Magento 1.9 version?

**Comment by mach-kernel** [comment]
@Outdoorsman, I believe that the end result of this case was an incorrect configuration of Magento. Are you having this problem?

Additionally, the Magento extension API should be the same for all 1.x releases - it should work. I am going to close this issue out, however, if you experience any problems please submit another issue request. 

Thanks!
